### ISSUE TITLE
UnsupportedOperationException logging java.sql.Date objects

### ISSUE THREAD

**Issue by rturner-edjuster** [apache/logging-log4j2#1400]
## Description

When logging java.sql.Date objects, an UnsupportedOperationException is thrown. Change for LOG4J2-2297 may have introduced this fault.

## Configuration

**Version:** 2.20.0

(worked in 2.19.0)

**Operating system:** MacOS 13.2.1

**JDK:** Corretto 18

openjdk 18.0.2 2022-07-19
OpenJDK Runtime Environment Corretto-18.0.2.9.1 (build 18.0.2+9-FR)
OpenJDK 64-Bit Server VM Corretto-18.0.2.9.1 (build 18.0.2+9-FR, mixed mode, sharing)

## Logs

```
Caused by: java.lang.UnsupportedOperationException
        at java.sql/java.sql.Date.toInstant(Date.java:316)
        at org.apache.logging.log4j.message.ParameterFormatter.appendDate(ParameterFormatter.java:492)
        at org.apache.logging.log4j.message.ParameterFormatter.appendSpecialTypes(ParameterFormatter.java:485)
        at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:474)
        at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:449)
        at org.apache.logging.log4j.message.ParameterFormatter.formatMessage2(ParameterFormatter.java:192)
        at org.apache.logging.log4j.message.ParameterizedMessage.formatTo(ParameterizedMessage.java:227)
```

## Reproduction

final java.sql.Date date = new java.sql.Date(2023, 03, 28):
logger.info("Date: {}", date);  // crashes

**Comment by ppkarwasz** [comment]
Hi @rturner-edjuster,

This was reported as #1366 and corrected in #1378. You should be able to test the solution in the `2.20.1-SNAPSHOT` (on `https;//repository.apache.org/snapshots`).

**Comment by rturner-edjuster** [comment]
Thanks -- I failed to find that. I was just adding automated tests to `log4j-api-test`, and I noticed it was working just before your email came in.  :)

**Comment by ppkarwasz** [comment]
Thanks for your report anyway.

**Comment by mukulb82** [comment]
Hello @rturner-edjuster @ppkarwasz 

I am seeing this exception when using **Log4j 2.20.0** with SLF4J 2.0.9. this is still an issue and if i understand correctly, since Log4J 2.20.0 has been released for prod - [2.20.0](https://logging.apache.org/log4j/2.x/release-notes/2.20.0.html) (2023-02-17) , which version is recommended to 

a) Could you confirm **the observation of this issue** - java.lang.UnsupportedOperationException on Log4J 2.20.0 is correct since the required fix might not be promoted to production and is still in SNAPSHOT version?

b) When is the expected fix for this defect appear and with which version?

c) could you provide any recommendation on previous log4j2 version which doesnt not have this issue? please confirm from the description above if  2.19.0 is good to take?

Thanks

**Comment by ppkarwasz** [comment]
@mukulb82,

Yes, the bug was introduced somewhere in January, so 2.19.0 should not be affected, but you can simply check with the code provided by the reporter. Check also #1788 for an ETA for the next release.
